# Generated by Django 5.2.8 on 2025-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_cookingstep_ingredient_recipe_delete_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
