# Generated by Django 5.2.8 on 2025-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author_name',
            field=models.CharField(default='Аноним', max_length=100, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
    ]
